/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BasicTraining`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/intervals`; params?: Router.UnknownInputParams; } | { pathname: `/LearnTheMethod`; params?: Router.UnknownInputParams; } | { pathname: `/maqamat`; params?: Router.UnknownInputParams; } | { pathname: `/playground`; params?: Router.UnknownInputParams; } | { pathname: `/../DevSplash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Dictations/Dictaionsplay`; params?: Router.UnknownInputParams; } | { pathname: `/Dictations`; params?: Router.UnknownInputParams; } | { pathname: `/IntroGame`; params?: Router.UnknownInputParams; } | { pathname: `/IntroGame/Level1`; params?: Router.UnknownInputParams; } | { pathname: `/IntroGame/Overview`; params?: Router.UnknownInputParams; } | { pathname: `/Training`; params?: Router.UnknownInputParams; } | { pathname: `/Training/listen`; params?: Router.UnknownInputParams; } | { pathname: `/Training/play`; params?: Router.UnknownInputParams; } | { pathname: `/Training/TrainingScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/BasicTraining`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/intervals`; params?: Router.UnknownOutputParams; } | { pathname: `/LearnTheMethod`; params?: Router.UnknownOutputParams; } | { pathname: `/maqamat`; params?: Router.UnknownOutputParams; } | { pathname: `/playground`; params?: Router.UnknownOutputParams; } | { pathname: `/../DevSplash`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Dictations/Dictaionsplay`; params?: Router.UnknownOutputParams; } | { pathname: `/Dictations`; params?: Router.UnknownOutputParams; } | { pathname: `/IntroGame`; params?: Router.UnknownOutputParams; } | { pathname: `/IntroGame/Level1`; params?: Router.UnknownOutputParams; } | { pathname: `/IntroGame/Overview`; params?: Router.UnknownOutputParams; } | { pathname: `/Training`; params?: Router.UnknownOutputParams; } | { pathname: `/Training/listen`; params?: Router.UnknownOutputParams; } | { pathname: `/Training/play`; params?: Router.UnknownOutputParams; } | { pathname: `/Training/TrainingScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/BasicTraining${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/intervals${`?${string}` | `#${string}` | ''}` | `/LearnTheMethod${`?${string}` | `#${string}` | ''}` | `/maqamat${`?${string}` | `#${string}` | ''}` | `/playground${`?${string}` | `#${string}` | ''}` | `/../DevSplash${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Dictations/Dictaionsplay${`?${string}` | `#${string}` | ''}` | `/Dictations${`?${string}` | `#${string}` | ''}` | `/IntroGame${`?${string}` | `#${string}` | ''}` | `/IntroGame/Level1${`?${string}` | `#${string}` | ''}` | `/IntroGame/Overview${`?${string}` | `#${string}` | ''}` | `/Training${`?${string}` | `#${string}` | ''}` | `/Training/listen${`?${string}` | `#${string}` | ''}` | `/Training/play${`?${string}` | `#${string}` | ''}` | `/Training/TrainingScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BasicTraining`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/intervals`; params?: Router.UnknownInputParams; } | { pathname: `/LearnTheMethod`; params?: Router.UnknownInputParams; } | { pathname: `/maqamat`; params?: Router.UnknownInputParams; } | { pathname: `/playground`; params?: Router.UnknownInputParams; } | { pathname: `/../DevSplash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Dictations/Dictaionsplay`; params?: Router.UnknownInputParams; } | { pathname: `/Dictations`; params?: Router.UnknownInputParams; } | { pathname: `/IntroGame`; params?: Router.UnknownInputParams; } | { pathname: `/IntroGame/Level1`; params?: Router.UnknownInputParams; } | { pathname: `/IntroGame/Overview`; params?: Router.UnknownInputParams; } | { pathname: `/Training`; params?: Router.UnknownInputParams; } | { pathname: `/Training/listen`; params?: Router.UnknownInputParams; } | { pathname: `/Training/play`; params?: Router.UnknownInputParams; } | { pathname: `/Training/TrainingScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
